/* typeScale, fullSizes, middlize, imageCover and responsiveImages helper scripts*/
function typeScale(){var a=window.innerWidth,b=document.getElementsByTagName("body")[0].style;b.fontSize=a/375+15+"px",b.lineHeight=a/8e3+1.4}function helperize(){$(".fullheight,.fullscreen").each(function(){var a=window.innerHeight;$(this).height(a)}),$(".middlize,.vmid").each(function(){var a=($(this).parent().height()-$(this).height())/2;$(this).css({top:a}),$(this).parent().css({overflow:"hidden"})}),$(".middlize").each(function(){var a=($(this).parent().width()-$(this).width())/2;$(this).css({left:a})}),$(".icovr").each(function(){var a=$(this).width(),b=$(this).height(),c=a/b,d=$(this).children("img")[0].naturalWidth,e=$(this).children("img")[0].naturalHeight,f=d/e;c>=f&&$(this).children("img").css({position:"relative",width:"100%",height:"auto",top:(b-e/(d/a))/2+"px",left:0}),f>c&&$(this).children("img").css({position:"relative",width:"auto",height:"100%",left:(a-d/(e/b))/2+"px",top:0})})}function makeImagesResponsive(){var a=document.getElementsByTagName("body")[0].getElementsByTagName("img");if(0!==a.length){var b;b=a[0].hasAttribute?function(a,b){return a.hasAttribute(b)}:function(a,b){return null!==a.getAttribute(b)};for(var c=window.devicePixelRatio?window.devicePixelRatio>=1.2?1:0:0,d=0;d<a.length;d++){var e=a[d],f=e.parentNode.offsetWidth,g=c&&b(e,"data-src2x")?"data-src2x":"data-src",h=c&&b(e,"data-src-base2x")?"data-src-base2x":"data-src-base";if(b(e,g)){for(var i=b(e,h)?e.getAttribute(h):"",j=e.getAttribute(g),k=j.split(","),l=0;l<k.length;l++){var m,n,o=k[l].replace(":","||").split("||"),p=o[0],q=o[1];if(-1!==p.indexOf("<"))if(m=p.split("<"),k[l-1]){var r=k[l-1].split(/:(.+)/),s=r[0].split("<");n=f<=m[1]&&f>s[1]}else n=f<=m[1];else if(m=p.split(">"),k[l+1]){var t=k[l+1].split(/:(.+)/),u=t[0].split(">");n=f>=m[1]&&f<u[1]}else n=f>=m[1];if(n){var v,w=-1!==q.indexOf("//")?1:0;v=1===w?q:i+q,e.src!==v&&e.setAttribute("src",v);break}}var x=a[d];x.addEventListener("load",helperize)}}}}window.addEventListener("load",makeImagesResponsive),window.addEventListener("load",helperize),window.addEventListener("resize",makeImagesResponsive),window.addEventListener("resize",helperize),window.addEventListener("resize",typeScale);




// inits. go here

$(function(){
  typeScale();
});
